# Generated by Django 5.1 on 2025-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('partida', models.TextField(verbose_name='Lugar de Partida')),
                ('destino', models.TextField(verbose_name='Lugar de Llegada')),
            ],
        ),
    ]
