# Generated by Django 5.1 on 2025-01-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0.3, max_digits=4, verbose_name='Precio'),
        ),
    ]
