# Generated by Django 5.1 on 2025-01-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='inicio',
        ),
        migrations.AddField(
            model_name='horario',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
    ]
