# Generated by Django 5.1 on 2025-01-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_remove_horario_inicio_horario_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
