# Generated by Django 5.1 on 2025-01-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0003_alter_horario_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='hora',
            field=models.TimeField(),
        ),
    ]
