# Generated by Django 5.1.4 on 2025-01-13 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_alter_horario_hora'),
        ('rutas', '0002_ruta_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='ruta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='rutas.ruta'),
        ),
    ]
