# Generated by Django 5.1.4 on 2025-01-13 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_horario_ruta'),
        ('rutas', '0002_ruta_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='ruta',
        ),
        migrations.AddField(
            model_name='horario',
            name='ruta',
            field=models.ManyToManyField(blank=True, null=True, to='rutas.ruta'),
        ),
    ]
