# Generated by Django 5.1.4 on 2025-01-13 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0006_remove_horario_ruta_horario_ruta'),
        ('rutas', '0002_ruta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='ruta',
            field=models.ManyToManyField(related_name='ruta_del_horario', to='rutas.ruta'),
        ),
    ]
