# Generated by Django 5.1.4 on 2025-01-13 03:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0007_alter_horario_ruta'),
        ('rutas', '0002_ruta_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='ruta',
        ),
        migrations.AddField(
            model_name='horario',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ruta_del_horario', to='rutas.ruta'),
        ),
    ]
