# Generated by Django 5.1.4 on 2025-01-13 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0008_remove_horario_ruta_horario_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='n_puestos',
            field=models.IntegerField(default=40, verbose_name='NÚMERO DE ASIENTOS'),
        ),
    ]
