# Generated by Django 5.1.4 on 2025-01-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0009_horario_n_puestos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='n_puestos',
        ),
    ]
