# Generated by Django 5.1.4 on 2025-01-12 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0016_remove_buses_horario'),
        ('horarios', '0004_alter_horario_hora'),
        ('rutas', '0002_ruta_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Viaje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='buses.buses', verbose_name='UNIDAD')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horarios.horario', verbose_name='HORARIO DEL VIAJE')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='rutas.ruta', verbose_name='RUTA')),
            ],
        ),
    ]
