# Generated by Django 5.1.4 on 2025-01-13 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0017_buses_horario'),
        ('horarios', '0004_alter_horario_hora'),
        ('rutas', '0002_ruta_precio'),
        ('viajes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buses.buses', verbose_name='UNIDAD'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='horarios.horario', verbose_name='HORARIO DEL VIAJE'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta', verbose_name='RUTA'),
        ),
    ]
