# Generated by Django 5.1.4 on 2025-01-13 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_alter_horario_hora'),
        ('viajes', '0002_alter_viaje_bus_alter_viaje_horario_alter_viaje_ruta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horario_viaje', to='horarios.horario', verbose_name='HORARIO DEL VIAJE'),
        ),
    ]
