# Generated by Django 5.1.4 on 2025-01-13 03:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0019_alter_buses_ruta'),
        ('horarios', '0004_alter_horario_hora'),
        ('rutas', '0002_ruta_precio'),
        ('viajes', '0003_alter_viaje_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viaje',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='buses.buses', verbose_name='UNIDAD'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='horario_viaje', to='horarios.horario', verbose_name='HORARIO DEL VIAJE'),
        ),
        migrations.AlterField(
            model_name='viaje',
            name='ruta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rutas.ruta', verbose_name='RUTA'),
        ),
    ]
