# Generated by Django 5.1.4 on 2025-01-13 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0004_alter_viaje_bus_alter_viaje_horario_alter_viaje_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viaje',
            name='ruta',
        ),
    ]
