# Generated by Django 5.1.4 on 2025-01-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viajes', '0005_remove_viaje_ruta'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='n_puestos',
            field=models.IntegerField(default=40, verbose_name='NÚMERO DE ASIENTOS'),
        ),
    ]
