# Generated by Django 5.1.3 on 2025-01-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=10, unique=True)),
                ('apellido1', models.CharField(max_length=150)),
                ('apellido2', models.CharField(max_length=150)),
                ('nombres', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
