# Generated by Django 5.1.3 on 2025-01-08 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buses',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=8, unique=True)),
                ('foto', models.ImageField(upload_to='buses/')),
                ('marca', models.CharField(max_length=50)),
                ('anio', models.PositiveIntegerField()),
            ],
        ),
    ]
