# Generated by Django 5.1.3 on 2025-01-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='foto',
            field=models.ImageField(default='bus.png', upload_to='buses/'),
        ),
    ]
