# Generated by Django 5.1.3 on 2025-01-08 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0002_alter_buses_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=30),
        ),
    ]
