# Generated by Django 5.1.3 on 2025-01-08 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0003_buses_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='asientos',
            field=models.PositiveIntegerField(default=40),
        ),
        migrations.CreateModel(
            name='Asientos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puestos', to='buses.buses')),
            ],
        ),
    ]
