# Generated by Django 5.1 on 2025-01-11 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0004_buses_asientos_asientos'),
        ('conductores', '0003_alter_conductores_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conductores.conductores'),
        ),
    ]
