# Generated by Django 5.1 on 2025-01-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0005_buses_conductor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='placa',
            field=models.CharField(max_length=8, unique=True, verbose_name='PLACA'),
        ),
    ]
