# Generated by Django 5.1 on 2025-01-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0006_alter_buses_placa'),
        ('conductores', '0003_alter_conductores_foto'),
        ('horarios', '0004_alter_horario_hora'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='horario',
            field=models.ManyToManyField(null=True, to='horarios.horario', verbose_name='HORAIOS'),
        ),
        migrations.AddField(
            model_name='buses',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.ruta', verbose_name='RUTA'),
        ),
        migrations.AlterField(
            model_name='buses',
            name='anio',
            field=models.PositiveIntegerField(verbose_name='AÑO DE LA UNIDAD'),
        ),
        migrations.AlterField(
            model_name='buses',
            name='asientos',
            field=models.PositiveIntegerField(default=40, verbose_name='¿CUÁNTOS ASIENTOS PARA PASAJEROS TIENE LA UNIDAD?'),
        ),
        migrations.AlterField(
            model_name='buses',
            name='conductor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='conductores.conductores', verbose_name='CONDUCTOR DE LA UNIDAD'),
        ),
        migrations.AlterField(
            model_name='buses',
            name='estado',
            field=models.CharField(default='ACTIVO', max_length=30, verbose_name='ESTADO DE LA UNIDAD'),
        ),
        migrations.AlterField(
            model_name='buses',
            name='foto',
            field=models.ImageField(default='bus.png', upload_to='buses/', verbose_name='FOTO DE LA UNIDAD'),
        ),
        migrations.AlterField(
            model_name='buses',
            name='marca',
            field=models.CharField(max_length=50, verbose_name='MARCA DE LA UNIDAD'),
        ),
    ]
