# Generated by Django 5.1 on 2025-01-11 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0008_alter_buses_ruta'),
        ('rutas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='rutas.ruta', verbose_name='RUTA'),
        ),
    ]
