# Generated by Django 5.1 on 2025-01-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0012_alter_buses_ruta'),
        ('horarios', '0004_alter_horario_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientos',
            name='ocupado',
            field=models.BooleanField(default=False, verbose_name='ASIENTO'),
        ),
        migrations.AlterField(
            model_name='buses',
            name='horario',
            field=models.ManyToManyField(null=True, to='horarios.horario', verbose_name='HORARIOS'),
        ),
    ]
