# Generated by Django 5.1 on 2025-01-12 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0013_asientos_ocupado_alter_buses_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='foto',
            field=models.ImageField(default='buses/bus.png', upload_to='buses/', verbose_name='FOTO DE LA UNIDAD'),
        ),
    ]
