# Generated by Django 5.1.4 on 2025-01-12 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0014_alter_buses_foto'),
        ('horarios', '0004_alter_horario_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='asientos',
            name='horario',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.RESTRICT, related_name='horario_asiento', to='horarios.horario'),
        ),
    ]
