# Generated by Django 5.1.4 on 2025-01-12 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0015_asientos_horario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='horario',
        ),
    ]
