# Generated by Django 5.1.4 on 2025-01-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0016_remove_buses_horario'),
        ('horarios', '0004_alter_horario_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='buses',
            name='horario',
            field=models.ManyToManyField(null=True, to='horarios.horario', verbose_name='HORARIOS'),
        ),
    ]
