# Generated by Django 5.1.4 on 2025-01-13 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0017_buses_horario'),
        ('rutas', '0002_ruta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='ruta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rutas.ruta', verbose_name='RUTA'),
        ),
    ]
