# Generated by Django 5.1.4 on 2025-01-13 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0019_alter_buses_ruta'),
        ('rutas', '0002_ruta_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buses',
            name='ruta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rutas.ruta', verbose_name='RUTA'),
        ),
    ]
