# Generated by Django 5.1.4 on 2025-01-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0021_alter_buses_ruta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buses',
            name='asientos',
        ),
        migrations.RemoveField(
            model_name='buses',
            name='ruta',
        ),
        migrations.AlterField(
            model_name='buses',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'ACTIVO'), ('NO ACTIVO', 'NO ACTIVO')], default='ACTIVO', max_length=30, verbose_name='ESTADO DE LA UNIDAD'),
        ),
    ]
