# Generated by Django 5.1 on 2025-01-12 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('buses', '0014_alter_buses_foto'),
        ('clientes', '0001_initial'),
        ('horarios', '0004_alter_horario_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='buses.asientos')),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='buses.buses', verbose_name='Unidad')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='clientes.cliente', verbose_name='Para qué cliente es el asiento?')),
                ('horario', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='horarios.horario', verbose_name='Horario')),
            ],
        ),
    ]
