# Generated by Django 5.1 on 2025-01-12 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0014_alter_buses_foto'),
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='asiento',
        ),
        migrations.AddField(
            model_name='venta',
            name='asiento',
            field=models.ManyToManyField(related_name='asientos', to='buses.asientos'),
        ),
    ]
