# Generated by Django 5.1 on 2025-01-11 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conductores',
            name='foto',
            field=models.ImageField(default='conductor_default.png', upload_to='conductores/'),
        ),
    ]
