# Generated by Django 5.1 on 2025-01-11 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conductores', '0002_conductores_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductores',
            name='foto',
            field=models.ImageField(default='conductores/conductor_default.png', upload_to='conductores/'),
        ),
    ]
